### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by SSebia** [TimeTopia/GTOS-Latest-Exe#2]
https://www.virustotal.com/gui/file/9f555ce030af5c115d6b5a20a63d91f8cbd230d9b0c930eee53e9c83ecae0603/detection
What is this? What did you bind + Github is for sharing sources and not like some kiddos submitting .exe files without any proof that it's legit, your file is a malware and virus total confirms it.

**Comment by TimeTopia** [comment]
ye sebia welcome ur own exe has virus admit it sucka
